name: win

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        shell: powershell
        run: |
          docker build . -f Dockerfile.windows -t ${{ env.REGISTRY }}/${{ github.repository }}-windows:latest
          docker push
